% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Mar-2017 10:26:52
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

cov_a = saveVarsMat.cov_a; % <160x160 double> too many elements

clear saveVarsMat;
